import { type NextPage } from "next";
import Head from "next/head";


const Home: NextPage = () => {

  return (
    <>
      <Head>
        <title>Demo admin auth without next-auth</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        Hello
      </div>
    </>
  );  
};

export default Home;
